@startuml UseCase

skinparam actorStyle awesome
left to right direction

:Пользователь: as P

package Авторизация {
    (Регистрация) as Register
    (Вход) as LogIn
    (Выход) as LogOut
}

package Склады {
    (Просмотр списка складов) as StorageList
    (Добавление склада) as CreateStorege
    (Удаление склада) as DeleteStorage
    (Просмотр хранимого на складе) as StorageContent
    (Отчет по складу) as StorageReport
}

package Элементы/Наборы {
    (Просмотр списка) as ElementList
    note top of ElementList : с разбивкой по категориям
    (Фильтр списка по строке) as ElementListFilter
    (Добавление элемента) as CreateElement
    (Формирование набора из элементов) as FormPack
    (Редактирование элемента/набора) as EditElement
    (Удаление элемента/набора) as DeleteElement
    (Просмотр элемента/набора) as CheckElement
    (Отчет по элементу/набору) as ElementReport
}

note "Включает в себя информацию\nо месте хранения и состоянии" as N1

N1 .. EditElement
N1 .. CreateElement
N1 .. FormPack

package Выдача/возврат {
    (Просмотр списка проектов) as DeliveryList
    (Просмотр проекта) as DeliveryCheck
    (Создание проекта) as CreateDelivery
    (Частичный возврат элементов из проекта)  as PartialReturn
    (Удаление проекта и возврат всех элементов на склад) as ReturnDeliveryToStorage
    (Отчет по ответсвенному) as LiableReport
}

package Логи {
    (Просмотр истории операций) as CheckLog
}

P --> Register
P --> LogIn
P --> LogOut

P --> DeliveryList
P --> DeliveryCheck
P --> CreateDelivery
P --> PartialReturn
P --> ReturnDeliveryToStorage
P --> LiableReport

StorageList <-- P
StorageContent <-- P
CreateStorege <-- P
DeleteStorage <- P : пустого
StorageReport <-- P

CheckElement <-- P
ElementList <-- P
ElementListFilter <-- P
CreateElement <-- P
EditElement <-- P
DeleteElement <-- P
ElementReport <-- P
FormPack <-- P

P --> CheckLog

@enduml