@startuml Диаграмма состояний
start

:открыть проект;
if() then (удаляем элемент)
repeat :выбрать элемент;

if(удаляем все элементы этого вида?) then (да)
:удалить элементы;
else (нет)
:указать новое кол-во (меньше текущего);
endif

repeat while (удалить еще) is (да)

:сохранить изменения;
:удаленные элементы
доступны на исхожном складе;

else (закрываем проект)
:закрыть проект;
:все входящие элементы доступны на иходном складе;
endif

stop
@enduml