@startuml Диаграмма состояний
start

:Начать добавление проекта;
:Описание проекта;
:Ответсвенный за проект;

repeat :добавить новый элемент;
:выбрать элемент;
:выбрать источник(склад)
откуда элемент будет взят;
:указать количество
не более чем есть на складе;

repeat while (добавить еще элементы?) is (да)
-> нет;
:забрать элементы со склада;
:создать проект;
:состояние элементов изменилось,
более не доступны на складе,
и используются в созданном проекте;

stop
@enduml