@startuml Диаграмма состояний
start

if (Пользователь авторизован?) then (нет)
    if (Пользователь зарегистрирован?) then (да)
        :Авторизация;
    else (нет)
        :Регистрация;
    endif
endif

repeat
:Пользователь авторизован;

split
    :Посмотр списка элементов
    или наборов элементов;
    if (Пользователь выбрал \nконкретный элемент?) then (да)
        :Просмотр информации о 
        выбранном элементе;
    endif

split again
    :Создание новой категории;
    :Ввод информации о категории;
    :Новая категория создана;

split again
    :Редактирование/удаление категории;
    :Категория изменена/удалена;

split again
    :Просмотреть список проектов;
        split
            :Создать новый проект;
            :Заполнить информацию
            добавить элементы;
            :Новый проект создан;

        split again
            :Удалить проект;
            :Проект удален,
            используемы элементы
            вернулись на склад;

        split again
            :Просмотреть информацию о проекте;
            if (Редактировать проект?) then(да)
                :проект изменен;
            else(нет)
            endif

        end split

split again
:Просмотр отчетов;
    split
        :Просмотр отчетов по месту хранения;
    split again
        :Просмотр отчетов по ответсвенному;
    split again
        :Просмотр отчетов по элементу;
        if (Редактировать элемент?) then(да)
            :Состояние, место хранения,
            использование элемента
            изменено;
        else(нет)
        endif
    end split

end split
repeat while (Работа завершена?)
-> да;



stop
@enduml