@startuml Диаграмма активности компонентов сервера
|Клиент|
start
:Отправляет запрос;

|API controller|
:Принимает запрос
на endpoint;

|DTOs|
:Преобразует данные 
из запроса в DTO;

|API controller|
:Осуществляет логику
работы приложения;

|Entity Framwork|
:Чтение/запись в БД;

|API controller|
:Осуществляет логику
работы приложения;

|DTOs|
:Преобразует результат 
работы в DTO;

|API controller|
:Отправляет ответ;

|Клиент|
:Принимает ответ;
stop
@enduml